### ISSUE TITLE
Trained models available

### ISSUE THREAD

**Issue by PaulBarZa** [kbrodt/competition-cervical-biopsy#1]
Hello @kbrodt !

I would like to test your model but we don't have access to the training images since the TissueNet competition is over.
Would it be possible for you to make your trained models available or not ?

Thanks for the future answer :)

**Comment by kbrodt** [comment]
Hi,

In the section `test` of `README` you may download the [trained models](https://disk.yandex.com/d/85zam_5YNLTcQg).

**Comment by PaulBarZa** [comment]
Oh thanks... I should learn to open my eyes better :/
Thank you and sorry for the inconvenience.
