### ISSUE TITLE
Download data with the download script?

### ISSUE THREAD

**Issue by guillaumejaume** [kbrodt/competition-cervical-biopsy#2]
Hi, 

I was wondering if the download script is expected to be functional. The path doesn't seem right. 

Thanks for your input! 
Guillaume

**Comment by kbrodt** [comment]
Hi Guillaume,

The competition was in 2020. I think they deleted the data from the s3 servers. Try asking the [host](https://www.drivendata.org/competitions/67/competition-cervical-biopsy/).

**Comment by guillaumejaume** [comment]
Thanks for the tip. Will do!
